service: api-graphql-fish

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-domain-manager

custom:
  serverless-offline:
    port: 4000
  webpackIncludeModules: true
  settings:
    domains:
      dev: "api.graphql.fish"
  customDomain:
    domainName: ${self:custom.settings.domains.${opt:stage, self:provider.stage}}
    basePath: ''
    stage: ${opt:stage, self:provider.stage}
    createRoute53Record: true

functions:
  graphql:
    handler: src/server.graphqlHandler
    events:
      - http:
          path: graphql
          method: POST
          cors: true
    environment:
      STAGE: "${opt:stage, self:provider.stage}"
  graphiql:
    handler: src/server.graphiqlHandler
    events:
      - http:
          path: graphiql
          method: GET
          cors: true
    environment:
      STAGE: "${opt:stage, self:provider.stage}"